# Generated by Django 6.0.2 on 2026-02-27 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderStatusTracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='order',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('order_received', 'Order Received'), ('packing', 'Packing'), ('ready_for_dispatch', 'Ready for Dispatch'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered')], default='order_received', max_length=30),
        ),
    ]
