# Generated by Django 6.0.2 on 2026-02-27 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderStatusTracking', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('received', 'Order Received'), ('packing', 'Packing'), ('ready_for_dispatch', 'Ready for Dispatch'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered')], default='received', max_length=30),
        ),
    ]
