# Generated by Django 5.2.8 on 2025-11-23 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_remove_customuser_username_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
