# Generated by Django 5.2.8 on 2025-12-20 04:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0003_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('customer', 'Customer'), ('delivery', 'Delivery Person')], default='admin', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pharmacydocument',
            name='citizenship',
            field=models.FileField(help_text='Upload citizenship document', upload_to='documents/citizenship/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='pharmacydocument',
            name='pan_number',
            field=models.FileField(help_text='Upload PAN card document', upload_to='documents/pan/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='pharmacydocument',
            name='pharmacy_license',
            field=models.FileField(help_text='Upload pharmacy license document', upload_to='documents/pharmacy_license/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])]),
        ),
    ]
