# Generated by Django 5.2.8 on 2026-01-23 10:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Billing', '0005_bill_payment_status_bill_transaction_id'),
        ('inventory', '0005_alter_medicine_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the gift', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of the gift', null=True)),
                ('value', models.DecimalField(decimal_places=2, help_text='Monetary value of the gift', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('image_url', models.URLField(blank=True, help_text='Image URL for the gift', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the gift is available')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gift',
                'verbose_name_plural': 'Gifts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the bonus scheme', max_length=255)),
                ('buy_quantity', models.PositiveIntegerField(help_text='Number of items to buy to qualify for bonus', validators=[django.core.validators.MinValueValidator(1)])),
                ('free_quantity', models.PositiveIntegerField(help_text='Number of free items given', validators=[django.core.validators.MinValueValidator(1)])),
                ('start_date', models.DateTimeField(help_text='When the bonus becomes active')),
                ('end_date', models.DateTimeField(help_text='When the bonus expires')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the bonus is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medicine', models.ForeignKey(help_text='Medicine this bonus applies to', on_delete=django.db.models.deletion.CASCADE, related_name='bonuses', to='inventory.medicine')),
            ],
            options={
                'verbose_name': 'Bonus',
                'verbose_name_plural': 'Bonuses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BillScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the scheme', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of the scheme', null=True)),
                ('min_bill_amount', models.DecimalField(decimal_places=2, help_text='Minimum bill amount required to qualify', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('gift_value_limit', models.DecimalField(decimal_places=2, help_text='Maximum value of gifts that can be selected', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('start_date', models.DateTimeField(help_text='When the scheme becomes active')),
                ('end_date', models.DateTimeField(help_text='When the scheme expires')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the scheme is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gifts', models.ManyToManyField(blank=True, help_text='Available gifts for this scheme', related_name='schemes', to='bonus_schemes.gift')),
            ],
            options={
                'verbose_name': 'Bill Scheme',
                'verbose_name_plural': 'Bill Schemes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AppliedBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_applied', models.PositiveIntegerField(help_text='How many times this bonus was applied', validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_bonuses', to='Billing.bill')),
                ('bonus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_to_bills', to='bonus_schemes.bonus')),
            ],
            options={
                'verbose_name': 'Applied Bonus',
                'verbose_name_plural': 'Applied Bonuses',
                'unique_together': {('bill', 'bonus')},
            },
        ),
        migrations.CreateModel(
            name='AppliedScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_gift_value', models.DecimalField(decimal_places=2, default=0.0, help_text='Total value of selected gifts', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_schemes', to='Billing.bill')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_to_bills', to='bonus_schemes.billscheme')),
                ('selected_gifts', models.ManyToManyField(blank=True, help_text='Gifts selected by customer', related_name='selected_in_applied_schemes', to='bonus_schemes.gift')),
            ],
            options={
                'verbose_name': 'Applied Scheme',
                'verbose_name_plural': 'Applied Schemes',
                'unique_together': {('bill', 'scheme')},
            },
        ),
    ]
