# Generated by Django 5.2.8 on 2026-01-23 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonus_schemes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billscheme',
            name='end_date',
            field=models.DateField(help_text='When the scheme expires'),
        ),
        migrations.AlterField(
            model_name='billscheme',
            name='start_date',
            field=models.DateField(help_text='When the scheme becomes active'),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='end_date',
            field=models.DateField(help_text='When the bonus expires'),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='start_date',
            field=models.DateField(help_text='When the bonus becomes active'),
        ),
    ]
