# Generated by Django 5.2.8 on 2026-02-05 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonus_schemes', '0001_initial'),
        ('inventory', '0005_alter_medicine_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='billscheme',
            name='medicine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='BillScheme', to='inventory.medicine'),
        ),
    ]
