# Generated by Django 5.2.8 on 2026-02-06 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bonus_schemes', '0002_billscheme_medicine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billscheme',
            name='medicine',
        ),
    ]
