# Generated by Django 5.2.8 on 2026-01-15 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billing', '0002_alter_bill_discount_alter_bill_subtotal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('due', 'Due')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='bill',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
