# Generated by Django 5.2.8 on 2026-01-16 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Billing', '0003_bill_payment_status_bill_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='transaction_id',
        ),
    ]
