# Generated by Django 5.2.8 on 2026-01-10 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL of the medicine image stored in cloud storage', max_length=500, null=True),
        ),
    ]
