# Generated by Django 5.2.8 on 2026-01-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_medicine_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='category',
            field=models.CharField(blank=True, help_text='General category name', max_length=100, null=True),
        ),
    ]
