# Generated by Django 5.2.8 on 2026-01-10 12:50

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_medicine_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='image_url',
        ),
        migrations.AddField(
            model_name='medicine',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Medicine image stored in Cloudinary', max_length=255, null=True, verbose_name='medicine_image'),
        ),
    ]
