# Generated by Django 6.0.2 on 2026-03-15 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_medicine_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonalMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(choices=[('Winter', 'Winter'), ('Spring', 'Spring'), ('Summer', 'Summer'), ('Autumn', 'Autumn')], max_length=20)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasonal_mappings', to='inventory.medicine')),
            ],
            options={
                'verbose_name': 'Seasonal Medicine',
                'verbose_name_plural': 'Seasonal Medicines',
                'unique_together': {('medicine', 'season')},
            },
        ),
    ]
